apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-prometheus
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |-
    apiVersion: 1
    
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
        isDefault: false
        version: 1
        editable: true
        uid: prometheus
        jsonData:
          timeInterval: "30s"