apiVersion: v1
kind: Service
metadata:
  name: alertmanager-discord-bridge
  namespace: monitoring
spec:
  selector:
    app: alertmanager-discord-bridge
  ports:
    - port: 9094
      targetPort: 9094